spring:
  profiles.active: dev
  application.name: @project.artifactId@

  flyway:
    placeholder-replacement: false

server:
  port: ${PORT:5000}

springdoc:
  swagger-ui:
    path: /v3/swagger-ui
    urls-primary-name: one
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
